apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: oc-pipeline-demo-3
  name: oc-pipeline-demo-3
spec:
  to:
    kind: Service
    name: oc-pipeline-demo-3
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
