apiVersion: v1
kind: Service
metadata:
  labels:
    app: oc-pipeline-demo-3
  name: oc-pipeline-demo-3
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: oc-pipeline-demo-3
